Object lock object retention
aquarist-labs/ceph pull request #111
Opened 2023-01-26 14:43 UTC by giubacc

work in progress

Fixes: https://github.com/aquarist-labs/s3gw/issues/228
Signed-off-by: Giuseppe Baccini <giuseppe.baccini@suse.com>

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

- If you are submitting a fix for a stable branch (e.g. "pacific"), please refer to [Submitting Patches to Ceph - Backports](https://github.com/ceph/ceph/blob/master/SubmittingPatches-backports.rst) for the proper workflow.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Component impact
  - [ ] Affects [Dashboard](https://tracker.ceph.com/projects/dashboard/issues/new), opened tracker ticket
  - [ ] Affects [Orchestrator](https://tracker.ceph.com/projects/orchestrator/issues/new), opened tracker ticket
  - [x] No impact that needs to be tracked
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

<details>
<summary>Show available Jenkins commands</summary>

- `jenkins retest this please`
- `jenkins test classic perf`
- `jenkins test crimson perf`
- `jenkins test signed`
- `jenkins test make check`
- `jenkins test make check arm64`
- `jenkins test submodules`
- `jenkins test dashboard`
- `jenkins test dashboard cephadm`
- `jenkins test api`
- `jenkins test docs`
- `jenkins render docs`
- `jenkins test ceph-volume all`
- `jenkins test ceph-volume tox`
- `jenkins test windows`
</details>

2023-02-24 10:32 UTC, irq0 requested changes
Commit message: Tested not verified? Verification means something way stronger (https://en.wikipedia.org/wiki/Software_verification)

Lines are a bit long
See: https://github.com/ceph/ceph/blob/main/CodingStyle
https://google.github.io/styleguide/cppguide.html
Consider running the python code through `black`

2023-02-24 10:32 UTC, irq0 commented on qa/rgw/store/sfs/tests/test-sfs-object-locking.py
> +# Copyright 2023 SUSE, LLC.
shebang?

2023-02-24 10:32 UTC, irq0 commented on src/rgw/driver/sfs/writer.cc
> +  /*if not defined on the object itself, set the bucket's object-locking profile, if enabled*/
Hard to understand with the 'if enabled' at the end

2023-02-24 10:32 UTC, irq0 commented on qa/rgw/store/sfs/tests/test-sfs-object-locking.py
> +        time.sleep(2)
Consider removing or adding a comment on why the tests have to wait 2 seconds between list versions and delete. (here and further down)

2023-02-28 08:33 UTC, giubacc commented
> Commit message: Tested not verified? Verification means something way stronger (https://en.wikipedia.org/wiki/Software_verification)
> 
> Lines are a bit long See: https://github.com/ceph/ceph/blob/main/CodingStyle https://google.github.io/styleguide/cppguide.html Consider running the python code through `black`

Rephrased with "Tested" and formatted py code with black

2023-03-02 11:29 UTC, irq0 approved these changes

2023-03-02 11:46 UTC, merged