sfs/writer: Error handling and recovery
aquarist-labs/ceph pull request #119
Opened 2023-02-16 09:01 UTC by irq0

Replace iostream code with cstyle alternatives that don't throw and are closer to how ceph src/os does IO. Handle errors during open/close/write by deleting the failed file and returning an error.

Convert errno errors to S3 errors where it makes sense.

fsync directories after creating deleting the object file.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [ ] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [ ] No tests

2023-02-17 12:56 UTC, irq0 commented
Looking for some general feedback and there is one thing open:
What to do with the database metadata on failure?
Right now the patch deletes the data, but keeps the metadata in state WRITING

1. keep it - let the GC remove partial objects
2. remove on failure
3. only create after the write is finished

2023-02-23 06:02 UTC, jecluis requested changes
Generally looks good, but I think the errors need to be logged at `-1` instead of `10` so they are not lost when running in production environments.

Also needs tests.

2023-02-23 06:02 UTC, jecluis commented on src/rgw/driver/sfs/writer.cc
> +  ret = ::fsync(fd);
maybe assert before that `fd >= 0`?

2023-02-23 06:02 UTC, jecluis commented on src/rgw/driver/sfs/writer.cc
> +    lsfs_dout(dpp, 10)
if we're logging failures, might be better to log them to level `-1`. Would be nice to have defined an `lsfs_derr()` macro, but given that's not available, logging to `-1` would suffice. Otherwise these errors will be hidden most of the time in a production environment.

2023-02-23 06:02 UTC, jecluis commented on src/rgw/driver/sfs/writer.cc
> +  lsfs_dout(dpp, 10) << "data len: " << data.length() << ", offset: " << offset
why are we using `fmt::format()` pretty much everywhere else, but falling back to the `<<` operator here?

2023-02-23 06:06 UTC, jecluis commented
> Looking for some general feedback and there is one thing open: What to do with the database metadata on failure? Right now the patch deletes the data, but keeps the metadata in state WRITING
> 
> 1. keep it - let the GC remove partial objects. mark "FAILED"
> 2. remove on failure
> 3. only create after the write is finished
> 
> I tend to favor 1., because we could easily display a list of failed uploads and their reasons on a status page

I would agree, although in case of an `ENOSPC` that might not be feasible. I'm not sure how we're going to update the DB if an `ENOSPC` is hit. Hopefully we stop writing once the disk is at `ENOSPC - some%` to avoid a situation where we're no longer able to write/rm stuff, but from the looks of this patch set it seems to me that if we hit `ENOSPC`, then it's because the underlying system call is throwing `ENOSPC` for reals.

2023-03-02 14:29 UTC, irq0 commented
I'm putting this on hold until #124 is in

2023-03-07 08:43 UTC, jecluis commented
> I'm putting this on hold until #124 is in

making it a draft until then.

2023-03-22 16:06 UTC, irq0 commented on src/rgw/driver/sfs/writer.cc
> +  ret = ::fsync(fd);
:+1:

2023-03-22 16:22 UTC, irq0 commented on src/rgw/driver/sfs/writer.cc
> +    lsfs_dout(dpp, 10)
:+1:

2023-03-22 16:23 UTC, irq0 commented on src/rgw/driver/sfs/writer.cc
> +  lsfs_dout(dpp, 10) << "data len: " << data.length() << ", offset: " << offset
no reason. Adding a commit that converts the longer log lines to fmt

2023-03-22 17:06 UTC, irq0 commented
> Also needs tests.

Unit testing would be painful, as we would need to mock / fake the io functions, no?

We probably get most bang for buck with adding a test suite that uses an error injection filesystem. We need to do this eventually to at minimum ensure that we don't crash under IO errors, etc.

Charybdefs has a nice example that fits the ENOSPC our use case that illustrates what I mean: https://github.com/scylladb/charybdefs/blob/master/tests/out_of_disk_space_test.py

2023-03-23 07:49 UTC, jecluis commented
I'll be happy to re-review this once the other 2 PRs are merged.

2023-04-04 07:34 UTC, jhmarina commented
All the PRs mentioned have been merged. @jecluis @irq0 is this ready for a re-review?

2023-04-04 07:48 UTC, irq0 commented
> All the PRs mentioned have been merged. @jecluis @irq0 is this ready for a re-review?

Yes

2023-04-14 17:15 UTC, jecluis approved these changes
lgtm but with a caveat: IMO we should cleanup the written file only when we are the ones creating it. If the file already existed (and assuming no versioning enabled), we should not be removing the file during cleanup.

2023-04-17 09:53 UTC, merged