rgw/sfs: Add unique indices on objects, versioned_objects
aquarist-labs/ceph pull request #126
Opened 2023-03-01 15:49 UTC by irq0

Make objects (bucket_id, name) and versioned_object (object_id, version_id) unique.

When violated sqlite_orm throws a system_error, catched and converted to an internal server error.

2023-03-23 07:36 UTC, jecluis requested changes

2023-03-23 07:36 UTC, jecluis commented on src/rgw/driver/sfs/sqlite/dbconn.h
> +      ),
I suspect these field names are missing a `b`, as in `vobjs_object_id_idx` instead of `vojs_*` ?

2023-03-23 09:00 UTC, irq0 commented on src/rgw/driver/sfs/sqlite/dbconn.h
> +      ),
I knew something was odd with the index names. Thanks for pointing out. Definitely better with a 'b'

2023-03-24 14:07 UTC, jecluis approved these changes

2023-03-24 14:15 UTC, merged