rgw/sfs: rename simplefile to sfs
aquarist-labs/ceph pull request #13
Opened 2022-06-28 10:03 UTC by jecluis

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

2022-06-28 10:52 UTC, 0xavi0 requested changes
I get a compilation issue:
```bash
/home/xavi/dev/joao/ceph/src/rgw/rgw_main.cc:635:12: error: expected primary-expression before ‘)’ token
  635 |   if (rados) { /* Supported for only RadosStore */
      |            ^
```

2022-06-28 10:52 UTC, 0xavi0 commented on src/rgw/rgw_sal_sfs.cc
>                    << dendl;
So far, this is the only place I still found `simplefile` references.

2022-06-28 10:52 UTC, 0xavi0 commented on src/rgw/store/sfs/bucket.h
>    RGWAccessControlPolicy acls;
Also, here, but it's commented. I would maybe remove this line or change it if we want to keep it, so there are no traces of old `simplefile` naming

2022-06-28 10:55 UTC, jecluis commented
weird, I didn't hit any compilation issues. oh well, I'll check it out. :shrug: 

thanks! :)

2022-06-28 10:59 UTC, 0xavi0 commented
In this line I would remove the comment or change it to be SFS of we want to keep it. 

https://github.com/jecluis/ceph/blob/96ebf991dd3f03d3348d3119fd2cc32d9b27706d/src/rgw/store/sfs/bucket.h#L39

2022-06-28 15:15 UTC, 0xavi0 requested changes

2022-06-28 15:15 UTC, 0xavi0 commented on src/rgw/store/sfs/sqlite/sqlite_users.cc
> +  auto rgw_SFS_path = ceph_context_->_conf.get_val<std::string>("rgw_SFS_data_path");
this one should be `rgw_sfs_data_path`, otherwise it crashes when accessing the DB path

2022-06-29 08:58 UTC, 0xavi0 approved these changes
After fixing the 2 major issues it passes the smoke tests.
I could not find any other `simplefile` reference, so LGTM.

2022-07-04 15:20 UTC, giubacc commented
> @giubacc try adding the `rgw_sfs_data_path` parameter. Maybe there is something wrong with the default value for it... I will also investigate.
> 
> for example:
> 
> ```shell
> --rgw_sfs_data_path=/tmp/sfs
> ```

That's weird, I have try every combination `-` and `--` but that parameter `rgw_sfs_data_path` seems having no effect on my running process.
It tries to always create the sqlile file at: `/var/lib/ceph/radosgw/`

```
2022-07-04T15:12:12.889+0000 7ffff3fcce00  0 rgw dbstore: DB initialization full db_path("/var/lib/ceph/radosgw/dbstore-default_ns")
2022-07-04T15:12:12.889+0000 7ffff3fcce00  0 rgw DBStore backend: Cant open /var/lib/ceph/radosgw/dbstore-default_ns.db; Errmsg - unable to open database file
2022-07-04T15:12:12.889+0000 7ffff3fcce00  0 rgw DBStore backend: sqlite exec failed for schema(PRAGMA foreign_keys=ON); Errmsg - 
2022-07-04T15:12:12.889+0000 7ffff3fcce00  0 rgw DBStore backend: sqlite exec failed for schema(CREATE TABLE IF NOT 
...
2022-07-04T15:12:12.889+0000 7ffff3fcce00  0 rgw DBStore backend: CreateUserTable failed
2022-07-04T15:12:12.889+0000 7ffff3fcce00  0 rgw DBStore backend: sqlite exec failed for schema(DROP TABLE IF EXISTS '/var/lib/ceph/radosgw/dbstore-default_ns_user_table'); Errmsg - 
2022-07-04T15:12:12.889+0000 7ffff3fcce00  0 rgw DBStore backend: DeleteUserTable failed 
2022-07-04T15:12:12.889+0000 7ffff3fcce00  0 rgw DBStore backend: Creation of tables failed
2022-07-04T15:12:12.889+0000 7ffff3fcce00  0 rgw DBStore backend: DB successfully initialized - name:/var/lib/ceph/radosgw/dbstore-default_ns
```
Everything is failing when starting up but in the end it says `successfully initialized` :D 
@0xavi0 can you check where is it trying to create the db file on your env?

2022-07-04 15:29 UTC, giubacc commented
Ugh.. I just realized that my build is probably faulty because there is no `WITH_RADOSGW_SFS` flag enabled :) .
So please, ignore all my previous comments until I verified my build configuration.

2022-07-04 16:18 UTC, giubacc commented
Completely rebuilt the executable and now it is working as expected.
`rgw_sfs_data_path` is working well when you are not using the default.
LGTM

2022-07-04 16:21 UTC, giubacc approved these changes

2022-07-05 09:39 UTC, merged