Remove WRITING state
aquarist-labs/ceph pull request #135
Opened 2023-03-22 16:58 UTC by irq0

Based on #124. Only relevant commits are the two with WRITING in the message

Removes the WRITING state, as we don't actually use it, but updating it wastes a lot of cycles.

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [x] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

2023-03-23 07:46 UTC, jecluis requested changes

2023-03-23 07:46 UTC, jecluis commented on src/rgw/driver/sfs/object_state.h
Let's just drop the thing, no need to be compatible with existing databases.

We can start carrying stuff for compatibility reasons when we decide the database format is stable. :)

2023-03-23 09:19 UTC, irq0 commented on src/rgw/driver/sfs/object_state.h
:+1:

2023-03-24 14:05 UTC, jecluis approved these changes

2023-03-24 14:14 UTC, merged