sfs: add a changelog
aquarist-labs/ceph pull request #16
Opened 2022-07-13 06:18 UTC by jecluis

Signed-off-by: Joao Eduardo Luis \<joao@suse.com>

2022-07-13 20:51 UTC, jecluis commented
let's merge this before building the final container for v0.1.0

2022-07-14 07:06 UTC, 0xavi0 approved these changes
LGTM

2022-07-14 07:42 UTC, giubacc requested changes

2022-07-14 07:42 UTC, giubacc commented on src/rgw/store/sfs/CHANGELOG.md
> +## [0.1.0]
```suggestion
## [0.1.0] - 2022-07-14
```

2022-07-14 09:18 UTC, giubacc approved these changes
LGTM

2022-07-14 09:19 UTC, merged