rgw/sfs: retry: move m_failed_error above
aquarist-labs/ceph pull request #177
Opened 2023-07-28 14:43 UTC by irq0

Follow up to #173

Signed-off-by: Marcel Lauhoff <marcel.lauhoff@suse.com>Mixed bag of quality, testing and quality of life improvements.

Highlights:
 - -Werror, -Wextra+friends
 - const most of types.h
 - ostream operators for DBObject, DBVersionedObject
 - Microbenchmarks for things we run a lot

## Checklist
- Tracker (select at least one)
  - [ ] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [x] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [x] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

2023-07-28 15:16 UTC, irq0 commented
The compiler warning commit needs some work. I tested it with clang, but gcc wants other settings / had different defaults:

GCC needs:
-Werror=missing-field-initializers
GCC does not like:
-Wno-error=unqualified-std-cast-call

2023-08-10 21:26 UTC, jecluis requested changes
few things caught my eye, but generally looks good

2023-08-10 21:26 UTC, jecluis commented on src/rgw/driver/sfs/bucket.cc
> +  // JSONDecoder::decode_json("multipart", multipart, obj);
drop the comment

2023-08-10 21:26 UTC, jecluis commented on src/rgw/driver/sfs/bucket.cc
> +                       // encode_json("multipart", multipart, f);
drop this comment

2023-08-10 21:26 UTC, jecluis commented on src/rgw/driver/sfs/sfs_lc.h
> +      const DoutPrefixProvider* /* dpp */, utime_t dur, optional_yield /* y */
drop commented out parameters?

2023-08-10 21:26 UTC, jecluis commented on src/rgw/driver/sfs/writer.cc
> +    bool* canceled, optional_yield /* y */
drop commented parameter names?

2023-08-11 10:00 UTC, jecluis approved these changes

2023-08-11 13:36 UTC, irq0 commented
Last test failures were s3 test test_lifecycle_expiration_versioned_tags2
Could repoduce the fail on aquarist-labs/s3gw as well for a while. Weird, likely flaky. Issue: https://github.com/aquarist-labs/s3gw/issues/670

2023-08-14 13:38 UTC, irq0 commented
Reproduced the test fail on aquarist-labs/s3gw with and without this PR. Merging this, to get it out of the way.
Fix for the LC S3 test coming up in a separate PR

2023-08-14 13:38 UTC, merged