rgw/sfs: ensure all SFS and related code has WITH_RADOSGW_SFS guards
aquarist-labs/ceph pull request #227
Opened 2023-10-12 08:26 UTC by tserong

Note that this lumps the status page and telemetry in with SFS, which may not be strictly correct as I assume the status page could be a useful feature independently of SFS.  That said, this somewhat heavy handed approach does as least mean radosgw now successfully builds if you run `cmake -DWITH_RADOSGW_SFS=OFF`.

2023-10-12 08:47 UTC, tserong commented
Wait a minute, that's not quite right...

2023-10-12 09:07 UTC, tserong commented
...OK, that's better.

2023-10-12 11:21 UTC, jecluis requested changes
looks reasonable to me, except that duplicate on dbstore stuff?

2023-10-12 11:21 UTC, jecluis commented on src/rgw/CMakeLists.txt
> +  list(APPEND librgw_common_srcs rgw_sal_dbstore.cc)
what?

2023-10-12 11:31 UTC, tserong commented on src/rgw/CMakeLists.txt
> +  list(APPEND librgw_common_srcs rgw_sal_dbstore.cc)
I got no idea. Aliens, probably.

2023-10-13 03:37 UTC, tserong commented
Rebased

2023-10-13 06:30 UTC, jecluis approved these changes

2023-10-13 07:10 UTC, merged