Fix default retention mode with multipart uploaded objects
aquarist-labs/ceph pull request #254
Opened 2023-11-22 15:42 UTC by giubacc

When an object is uploaded with multipart, for object-lock enabled buckets,
the default rentention mode must be set in the object's attributes
(when a retention mode is not explicitely set by the user for the object).
Therefore, `RGW_ATTR_OBJECT_RETENTION` must be set in the attrs of each part
being uploaded in the `SFSMultipartUploadV2::complete()` function.
    
Fixes: https://github.com/aquarist-labs/s3gw/issues/761

## Contribution Guidelines
- To sign and title your commits, please refer to [Submitting Patches to Ceph](https://github.com/ceph/ceph/blob/main/SubmittingPatches.rst).

## Checklist
- Tracker (select at least one)
  - [x] References tracker ticket
  - [ ] Very recent bug; references commit where it was introduced
  - [ ] New feature (ticket optional)
  - [ ] Doc update (no ticket needed)
  - [ ] Code cleanup (no ticket needed)
- Documentation (select at least one)
  - [ ] Updates relevant documentation
  - [x] No doc update is appropriate
- Tests (select at least one)
  - [ ] Includes [unit test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/tests-unit-tests/)
  - [ ] Includes [integration test(s)](https://docs.ceph.com/en/latest/dev/developer_guide/testing_integration_tests/)
  - [ ] Includes bug reproducer
  - [x] No tests

2023-11-23 14:29 UTC, irq0 commented on src/rgw/driver/sfs/multipart.cc
> +      string mode = bucketref->get_info().obj_lock.get_mode();
std::string please

2023-11-23 14:33 UTC, irq0 commented on src/rgw/driver/sfs/multipart.cc
> +      real_time lock_until_date =
ceph::real_time please

2023-11-23 14:33 UTC, irq0 requested changes, later dismissed
Please namespace the types as we do in the rest of the code. Otherwise looks good

2023-12-04 09:56 UTC, jecluis approved these changes

2023-12-04 09:57 UTC, merged