ci: test and benchmark radosgw
aquarist-labs/ceph pull request #36
Opened 2022-09-07 13:30 UTC by m-ildefons

- Run more extensive tests as part of the PR validation worklow
- Run benchmarks after pushes (merges) to branch s3gw

Signed-off-by: Moritz Röhrich <moritz.rohrich@suse.com>

2022-09-08 10:10 UTC, jhmarina submitted a review, later dismissed

2022-09-13 04:29 UTC, jecluis approved these changes
lgtm, but requires https://github.com/aquarist-labs/s3gw-tools/pull/164 to be merged first

2022-10-06 22:27 UTC, jecluis submitted a review, later dismissed
good to merge once its sibling PR on s3gw-tools is merged

2022-11-06 15:09 UTC, jecluis requested changes

2022-11-06 15:09 UTC, jecluis commented on .github/workflows/test-radosgw.yml
> +#           done < $S3TEST_CASES
do we really want to have these here?

2023-01-03 09:33 UTC, closed without merging